### PR TITLE
Menu page 2

### PR DESCRIPTION
**Pull request by chrissyt468**
Menu View Static page done + nav bar update

### CODE REVIEW

**Review by cassandrafrancisco — APPROVED** [review]
the menu page looks good!

**Review by osas-e — APPROVED** [review]
Looks good

**Review by Dipesh13857394 — APPROVED** [review]

**Review by MarcC2002 — APPROVED** [review]
Wow very nice!

**Review by mtdoan — APPROVED** [review]
Wonderful!

**Pull request merged**
